// Package traininglog records each request or response blocked by the WAF as
// structured JSON Lines. These records power a training report that explains
// what was attempted, how the input was decoded, and how DoBot Shield reacted.
//
// The logger is deliberately failure-tolerant. A write failure degrades only
// the logger and never interrupts request processing or changes a WAF decision.
package traininglog

import (
	"bufio"
	"bytes"
	"encoding/json"
	"log"
	"os"
	"path/filepath"
	"sync"
	"unicode/utf8"
)

// Event describes one block or monitor-mode detection. Its JSON tags define
// the on-disk schema consumed by the report generator.
type Event struct {
	Timestamp string   `json:"timestamp"`            // RFC3339 in UTC
	RequestID string   `json:"request_id,omitempty"` // correlation with access logs
	IP        string   `json:"ip"`                   // client origin
	Method    string   `json:"method,omitempty"`     // HTTP method (request phase only)
	Path      string   `json:"path,omitempty"`       // target path
	Phase     string   `json:"phase"`                // "request" or "response"
	Action    string   `json:"action"`               // "blocked" or "detected"
	Category  string   `json:"category"`             // threat category (XSS, SQLi, ...)
	Location  string   `json:"location,omitempty"`   // match location (Query, Body, Header, ...)
	Rule      string   `json:"rule"`                 // matched expression or rule identifier
	Payload   string   `json:"payload"`              // original input
	Variants  []string `json:"variants,omitempty"`   // variants generated by WAF decoders
}

// Size limits prevent large inputs from inflating logs and reports.
const (
	maxPayloadBytes = 8 * 1024
	maxRuleBytes    = 2 * 1024
	maxVariantBytes = 4 * 1024
	maxVariants     = 16
)

const truncationMark = "...(truncated)"

// Logger writes events to a JSON Lines file and is safe for concurrent use.
type Logger struct {
	mu       sync.Mutex
	file     *os.File
	path     string
	enabled  bool
	degraded bool
}

// New opens or creates a log file and its parent directories. On failure it
// returns a degraded logger that silently drops events, never nil or a panic.
func New(path string) *Logger {
	l := &Logger{path: path}
	if path == "" {
		l.degraded = true
		return l
	}

	if dir := filepath.Dir(path); dir != "" && dir != "." {
		if err := os.MkdirAll(dir, 0o700); err != nil {
			log.Printf("traininglog: could not create directory %q: %v", dir, err)
			l.degraded = true
			return l
		}
	}

	file, err := os.OpenFile(path, os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0o600)
	if err != nil {
		log.Printf("traininglog: could not open %q for writing: %v", path, err)
		l.degraded = true
		return l
	}
	if err := file.Chmod(0o600); err != nil {
		_ = file.Close()
		log.Printf("traininglog: could not restrict permissions for %q: %v", path, err)
		l.degraded = true
		return l
	}

	l.file = file
	l.enabled = true
	return l
}

// Enabled reports whether the logger is enabled and healthy.
func (l *Logger) Enabled() bool {
	if l == nil {
		return false
	}
	l.mu.Lock()
	defer l.mu.Unlock()
	return l.enabled && !l.degraded && l.file != nil
}

// Record serializes and writes an event. Any failure only degrades this logger.
func (l *Logger) Record(ev Event) {
	if l == nil {
		return
	}

	l.mu.Lock()
	defer l.mu.Unlock()

	if !l.enabled || l.degraded || l.file == nil {
		return
	}

	data, err := json.Marshal(sanitize(ev))
	if err != nil {
		return
	}
	data = append(data, '\n')

	if _, err := l.file.Write(data); err != nil {
		log.Printf("traininglog: event write failed; logging disabled: %v", err)
		l.degraded = true
	}
}

// Close releases the underlying file. It is safe to call more than once.
func (l *Logger) Close() error {
	if l == nil {
		return nil
	}
	l.mu.Lock()
	defer l.mu.Unlock()

	l.enabled = false
	if l.file == nil {
		return nil
	}
	err := l.file.Close()
	l.file = nil
	return err
}

// sanitize enforces size limits without mutating the caller's slices.
func sanitize(ev Event) Event {
	ev.Payload = truncate(ev.Payload, maxPayloadBytes)
	ev.Rule = truncate(ev.Rule, maxRuleBytes)

	if len(ev.Variants) > 0 {
		limit := len(ev.Variants)
		if limit > maxVariants {
			limit = maxVariants
		}
		variants := make([]string, limit)
		for i := 0; i < limit; i++ {
			variants[i] = truncate(ev.Variants[i], maxVariantBytes)
		}
		ev.Variants = variants
	}

	return ev
}

// truncate cuts a string to at most max bytes on a UTF-8 rune boundary and
// appends a marker when truncation occurs.
func truncate(s string, max int) string {
	if len(s) <= max {
		return s
	}

	cut := max
	for cut > 0 && !utf8.RuneStart(s[cut]) {
		cut--
	}
	return s[:cut] + truncationMark
}

// Load reads all events from a JSON Lines file. Blank or malformed lines are
// ignored so one corrupt record cannot invalidate an entire report.
func Load(path string) ([]Event, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer file.Close()

	var events []Event
	scanner := bufio.NewScanner(file)
	// Accommodate payloads and variants near the limits above.
	scanner.Buffer(make([]byte, 0, 64*1024), 2*1024*1024)

	for scanner.Scan() {
		line := bytes.TrimSpace(scanner.Bytes())
		if len(line) == 0 {
			continue
		}
		var ev Event
		if err := json.Unmarshal(line, &ev); err != nil {
			continue
		}
		events = append(events, ev)
	}

	if err := scanner.Err(); err != nil {
		return events, err
	}
	return events, nil
}

// The package-level logger lets middleware record events without changing its
// public signatures, similar to the standard log package.
var (
	defaultMu     sync.RWMutex
	defaultLogger *Logger
)

// Configure initializes or replaces the package-level logger. When disabled,
// Record becomes a no-op.
func Configure(enabled bool, path string) {
	defaultMu.Lock()
	defer defaultMu.Unlock()

	if defaultLogger != nil {
		_ = defaultLogger.Close()
		defaultLogger = nil
	}
	if !enabled {
		return
	}
	defaultLogger = New(path)
}

// Enabled reports whether the package-level logger is healthy.
func Enabled() bool {
	defaultMu.RLock()
	defer defaultMu.RUnlock()
	return defaultLogger.Enabled()
}

// Record writes an event through the package-level logger.
func Record(ev Event) {
	defaultMu.RLock()
	logger := defaultLogger
	defaultMu.RUnlock()
	logger.Record(ev)
}

// CloseDefault closes the package-level logger.
func CloseDefault() error {
	defaultMu.Lock()
	defer defaultMu.Unlock()
	if defaultLogger == nil {
		return nil
	}
	err := defaultLogger.Close()
	defaultLogger = nil
	return err
}
