package waf

import (
	"bytes"
	"io"
	"mime"
	"mime/multipart"
	"net/http"
	"regexp"
	"strings"
)

// Detection contains explanatory details for a decision already made by
// CheckRequest. It exposes the original input and every decoded variant used by
// the WAF without reevaluating the security decision.
type Detection struct {
	Category string   // for example, "XSS", "SQLi", or "CMD_INJ"
	Location string   // for example, "Query", "Body", or "Header User-Agent"
	Rule     string   // matched expression or identifier
	Payload  string   // raw value received in the matching field
	Variants []string // variants generated by WAF decoders
}

var sensitiveValuePattern = regexp.MustCompile(`(?i)(["']?(?:password|passwd|pwd|access[_-]?token|refresh[_-]?token|token|secret|api[_-]?key|authorization|session(?:id)?|cookie)["']?\s*(?:=|:)\s*)(?:"(?:\\.|[^"])*"|'(?:\\.|[^'])*'|[^&;\s,}]+)`)

// RedactDetection removes common credential and session values before a
// training event is persisted. Authorization and Cookie headers are always
// treated as wholly sensitive.
func RedactDetection(detection Detection) Detection {
	location := strings.ToLower(detection.Location)
	if strings.Contains(location, "header authorization") || strings.Contains(location, "header cookie") {
		detection.Payload = "[REDACTED]"
		detection.Variants = nil
		return detection
	}

	detection.Payload = redactSensitiveValues(detection.Payload)
	if len(detection.Variants) > 0 {
		variants := make([]string, len(detection.Variants))
		for index, variant := range detection.Variants {
			variants[index] = redactSensitiveValues(variant)
		}
		detection.Variants = variants
	}
	return detection
}

func redactSensitiveValues(value string) string {
	return sensitiveValuePattern.ReplaceAllString(value, `${1}[REDACTED]`)
}

// DescribeBlock builds details for a block already decided by CheckRequest. It
// accepts the same details and rule values, locates the matching original input
// on a best-effort basis, and derives its inspection variants. It is safe to
// call only for logging because it never changes the decision.
func DescribeBlock(r *http.Request, bodyBytes []byte, details, rule string) Detection {
	category, location := splitDetails(details)
	payload := locatePayload(r, bodyBytes, location)

	var variants []string
	if payload != "" {
		variants = buildInspectionVariants(payload)
	}

	return Detection{
		Category: category,
		Location: location,
		Rule:     rule,
		Payload:  payload,
		Variants: variants,
	}
}

// BuildVariants exposes the decoder chain used internally by WAF inspection.
func BuildVariants(input string) []string {
	return buildInspectionVariants(input)
}

// SplitDetails separates "Category in Location" into its two components.
func SplitDetails(details string) (category, location string) {
	return splitDetails(details)
}

// splitDetails handles both "XSS in Query" and standalone identifiers such as
// "MALFORMED_MULTIPART".
func splitDetails(details string) (category, location string) {
	const sep = " in "
	if idx := strings.Index(details, sep); idx >= 0 {
		return details[:idx], details[idx+len(sep):]
	}
	return details, ""
}

// locatePayload recovers the raw value at a location. For repeated headers or
// multipart fields, it selects the candidate that actually triggers inspection.
func locatePayload(r *http.Request, bodyBytes []byte, location string) string {
	if r == nil {
		if location == "Body" {
			return string(bodyBytes)
		}
		return ""
	}

	switch {
	case location == "Path":
		return r.URL.EscapedPath()
	case location == "Host":
		return r.Host
	case location == "Query":
		return r.URL.RawQuery
	case location == "Body":
		return string(bodyBytes)
	case strings.HasPrefix(location, "Header "):
		name := strings.TrimSpace(strings.TrimPrefix(location, "Header "))
		return locateHeaderPayload(r, name)
	case strings.HasPrefix(location, "Multipart"):
		return locateMultipartPayload(r, bodyBytes)
	default:
		return ""
	}
}

// locateHeaderPayload returns the first repeated header value that triggers an
// inspection group. Without a clear match, it joins all values.
func locateHeaderPayload(r *http.Request, name string) string {
	values := r.Header.Values(name)
	headerInjection := []patternGroup{{"HTTP_HEADER_INJECTION", headerInjectionPatterns}}

	for _, value := range values {
		if malicious, _, _ := analyzePayload(value); malicious {
			return value
		}
		if malicious, _, _ := analyzePayloadWithGroups(value, headerInjection); malicious {
			return value
		}
	}

	if len(values) > 0 {
		return strings.Join(values, " | ")
	}
	return ""
}

// locateMultipartPayload inspects already-read multipart bytes without touching
// r.Body and returns the first matching metadata or part content.
func locateMultipartPayload(r *http.Request, bodyBytes []byte) string {
	if len(bodyBytes) == 0 {
		return ""
	}

	mediaType, params, err := mime.ParseMediaType(r.Header.Get("Content-Type"))
	if err != nil || !strings.HasPrefix(strings.ToLower(mediaType), "multipart/") {
		return ""
	}
	boundary := params["boundary"]
	if boundary == "" {
		return ""
	}

	reader := multipart.NewReader(bytes.NewReader(bodyBytes), boundary)
	for i := 0; i < maxMultipartParts; i++ {
		part, err := reader.NextPart()
		if err != nil {
			return ""
		}

		for _, value := range []string{part.FormName(), part.FileName(), part.Header.Get("Content-Type")} {
			if malicious, _, _ := analyzePayload(value); malicious {
				_ = part.Close()
				return value
			}
		}

		content, err := io.ReadAll(io.LimitReader(part, maxMultipartPartBytes+1))
		_ = part.Close()
		if err != nil || len(content) == 0 {
			continue
		}
		if malicious, _, _ := analyzePayload(string(content)); malicious {
			return string(content)
		}
	}

	return ""
}
